pub mod body;
pub mod camera;
pub mod canvas;
pub mod color;
pub mod computed_intersection;
pub mod intersection;
pub mod light;
pub mod material;
pub mod matrix;
pub mod point;
pub mod ray;
pub mod sphere;
mod tuple;
pub mod utils;
pub mod vector;
pub mod world;
